routes/web.php
<?php

$this->redirect('/', '/admin');

$this->post('logout',  ['uses' => 'UserController@logout', 'as' => 'logout']);

$this->group(['middleware' => 'guest'], function ()
{
    $this->get('login', ['uses' => 'UserController@showLoginForm', 'as' => 'login']);
    $this->post('login', ['uses' => 'UserController@login']);

    $this->get('register', ['uses' => 'UserController@showRegistrationForm', 'as' => 'register']);
    $this->post('register', ['uses' => 'UserController@register']);

    $this->group(['prefix' => 'password'], function () {
        $this->get('reset', ['uses' => 'UserController@showLinkRequestForm', 'as' => 'password.request']);
        $this->post('email', ['uses' => 'UserController@sendResetLinkEmail', 'as' => 'password.email']);
        $this->get('reset/{token}', ['uses' => 'UserController@showResetForm', 'as' => 'password.reset']);
        $this->post('reset', ['uses' => 'UserController@reset']);
    });
});

$this->group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => 'auth'], function ()
{
    $this->get('/', ['uses' => 'DashboardController', 'as' => 'dashboard']);

    $this->resource('posts', 'PostController')->except([
        'edit', 'update', 'destroy'
    ]);

    $this->apiResource('comments', 'CommentController')->only([
        'store'
    ]);
});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'user_id', 'title', 'description'
    ];

    public function user()
    {
        return $this->belongsTo('App\User', 'user_id');
    }

    public function comments()
    {
        return $this->hasMany('App\Comment', 'post_id');
    }
}

app/Http/Controllers/Admin/PostController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\View\View;
use Illuminate\Http\Request;
use Illuminate\Http\RedirectResponse;

use App\Post;
use App\Http\Controllers\Controller;
use App\Forms\Handlers\PostFormHandler;
use App\Forms\Handlers\CommentFormHandler;

class PostController extends Controller
{
    private $templatePath = 'admin.posts.';

    private $postFormHandler;
    private $commentFormHandler;

    public function __construct(
        PostFormHandler $postFormHandler,
        CommentFormHandler $commentFormHandler
    )
    {
        $this->postFormHandler = $postFormHandler;
        $this->commentFormHandler = $commentFormHandler;
    }

    /**
     * Display a listing of the Posts.
     *
     * @return View
     */
    public function index() : View
    {
        return view("{$this->templatePath}index");
    }

    /**
     * Show the form for creating a new Post.
     *
     * @return View
     */
    public function create() : View
    {
        return view("{$this->templatePath}create", [
            'postForm' => $this->postFormHandler->create()
        ]);
    }

    /**
     * Store a newly created Post in storage.
     *
     * @param  Request  $request
     * @return RedirectResponse
     */
    public function store(Request $request) : RedirectResponse
    {
        $post = $this->postFormHandler->handle($request);
        if(!$post)
        {
            return redirect(route('admin.posts.index'))->withMessage([
                'type'    => 'error',
                'message' => 'Something goes wrong'
            ]);
        }

        return redirect(route('admin.posts.index'))->withMessage([
            'type'    => 'success',
            'message' => 'Action done'
        ]);
    }

    /**
     * Show specific Post.
     *
     * @param  Post  $post
     * @return View
     */
    public function show(Post $post) : View
    {
        return view("{$this->templatePath}show", compact('post'))
            ->with('commentForm', $this->commentFormHandler->create());
    }
}

resources/views/admin/posts/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="row justify-content-center my-4">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Post') }}</div>

                <div class="card-body">
                    {!! form($postForm) !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/posts/index.blade.php
@extends('layouts.app')

@section('content')

    <h1 class="my-4">
        @if($posts->count()>0)
            All posts
                <small>with comments inside</small>
        @else
            There is no posts.
        @endif
    </h1>

    @foreach($posts as $post)
        <!-- Blog Post -->
        <div class="card mb-4">
            <div class="card-body">
                <h2 class="card-title">{{ $post->title }}</h2>
                <p class="card-text">{{ $post->description }}</p>
                <a href="{{ route('admin.posts.show', ['post' => $post->id]) }}" class="btn btn-primary">Read More &rarr;</a>
            </div>
            <div class="card-footer text-muted">
                Posted on {{ $post->created_at->format('M d, Y, H:i:s') }}
            </div>
        </div>
    @endforeach
@endsection

resources/views/admin/posts/show.blade.php
@extends('layouts.app')

@section('content')

        <!-- Title -->
        <h1 class="mt-4">
            {{ $post->title }}
        </h1>

        <hr>
        <!-- Date/Time -->
        <p>
            Posted on {{ $post->created_at->format('M d, Y, H:i:s') }}
        </p>

        <hr>
        <!-- Post Content -->
        <p class="lead">
            {{ $post->description }}
        </p>

        <hr>
        <!-- Comments Form -->
        <div class="card my-4">
            <h5 class="card-header">Leave a Comment:</h5>
            <div class="card-body">
                {!! form_start($commentForm) !!}
                    {!! form_row($commentForm->post_id, ['value' => $post->id ]) !!}
                {!! form_end($commentForm) !!}
            </div>
        </div>

        @foreach($post->comments as $comment)
            <!-- Single Comment -->
            <div class="media mb-4">
                <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
                <div class="media-body">
                    <h5 class="mt-0">{{ $comment->user->name }}</h5>
                    {{ $comment->content }}
                </div>
            </div>
        @endforeach
@endsection